### ISSUE TITLE
Use a more recent GraalVM and use TruffleRuby Native

### ISSUE THREAD

**Issue by eregon** [vnmakarov/ruby#7]
Hello,

I noticed you recently updated the benchmarks results in the README.
However, the TruffleRuby results seem to still be measured with GraalVM 0.22, which is almost a year old now (the current release is GraalVM 0.31 as of writing).

Since the micro-benchmarks are measured with wall-clock time for the whole script and they are all rather short-running programs, it would be much more relevant to compare against [TruffleRuby Native](https://eregon.me/blog/2018/02/19/truffleruby-native-fast-short-scripts.html).

As a note, GraalVM 0.22 is the only release I'm aware of which is not running OptCarrot. It also had an unfortunate large performance regression notably on reading Ruby constants due to a bug in the Truffle DSL processor at the time.

So overall, I believe GraalVM 0.22 shows results which are quite different than the reality of recent GraalVM, and it would be much more interesting and relevant to compare to a recent GraalVM, with `--native`.

Could you use the latest GraalVM, in `--native` mode, for the next benchmark run?

**Comment by vnmakarov** [comment]
I updated the results for Graal using its version 0.31 without --native so far.  I'll have results with --native tomorrow and post them too.  

I found that my previous results for optcarrot with default number of frames were wrong.  They were actually for another run with 2000 frames.  I also corrected these results.

**Comment by eregon** [comment]
That's very interesting results, thank you for re-running the benchmarks!
I'm curious to see what the `--native` results look like.

**Comment by vnmakarov** [comment]
I've added results for Graal 0.31 with `--native` and did some analysis.  In overall --native is a very big step forward for Graal and MJIT desperately needs inlining and its implementation should be the highest priority task for MJIT to improve wall time performance.

**Comment by eregon** [comment]
Thank you for the results and analysis. Indeed, I'm delighted to see `--native` is looking great on wall time performance and for warmup on Optcarrot.
I'll close this issue, thank you for addressing it so quickly!
